smtp_server: 
    servername: "smtp.gmail.com"
    port: 587
    sender_email: "watchdog4monster@gmail.com"
    password: "watchmonster"

receivers:
    - "jie.li@ttu.edu"
    - "username0416@gmail.com"

target_server:
    - ip: "10.10.1.3"
      name: "Influx"
    - ip: "10.10.1.4"
      name: "Nagios"
    
