# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Interval(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, text=None, value=None):  # noqa: E501
        """Interval - a model defined in OpenAPI

        :param text: The text of this Interval.  # noqa: E501
        :type text: str
        :param value: The value of this Interval.  # noqa: E501
        :type value: str
        """
        self.openapi_types = {
            'text': str,
            'value': str
        }

        self.attribute_map = {
            'text': 'text',
            'value': 'value'
        }

        self._text = text
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'Interval':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Interval of this Interval.  # noqa: E501
        :rtype: Interval
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self):
        """Gets the text of this Interval.


        :return: The text of this Interval.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Interval.


        :param text: The text of this Interval.
        :type text: str
        """

        self._text = text

    @property
    def value(self):
        """Gets the value of this Interval.


        :return: The value of this Interval.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Interval.


        :param value: The value of this Interval.
        :type value: str
        """

        self._value = value
