# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TimeRange(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _from=None, to=None):  # noqa: E501
        """TimeRange - a model defined in OpenAPI

        :param _from: The _from of this TimeRange.  # noqa: E501
        :type _from: str
        :param to: The to of this TimeRange.  # noqa: E501
        :type to: str
        """
        self.openapi_types = {
            '_from': str,
            'to': str
        }

        self.attribute_map = {
            '_from': 'from',
            'to': 'to'
        }

        self.__from = _from
        self._to = to

    @classmethod
    def from_dict(cls, dikt) -> 'TimeRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TimeRange of this TimeRange.  # noqa: E501
        :rtype: TimeRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _from(self):
        """Gets the _from of this TimeRange.


        :return: The _from of this TimeRange.
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this TimeRange.


        :param _from: The _from of this TimeRange.
        :type _from: str
        """

        self.__from = _from

    @property
    def to(self):
        """Gets the to of this TimeRange.


        :return: The to of this TimeRange.
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this TimeRange.


        :param to: The to of this TimeRange.
        :type to: str
        """

        self._to = to
