# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class WebResponseMetrics(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, nodes_info=None, jobs_info=None, nodes_state=None, time_stamp=None):  # noqa: E501
        """WebResponseMetrics - a model defined in OpenAPI

        :param nodes_info: The nodes_info of this WebResponseMetrics.  # noqa: E501
        :type nodes_info: List[object]
        :param jobs_info: The jobs_info of this WebResponseMetrics.  # noqa: E501
        :type jobs_info: List[object]
        :param nodes_state: The nodes_state of this WebResponseMetrics.  # noqa: E501
        :type nodes_state: List[object]
        :param time_stamp: The time_stamp of this WebResponseMetrics.  # noqa: E501
        :type time_stamp: List[int]
        """
        self.openapi_types = {
            'nodes_info': List[object],
            'jobs_info': List[object],
            'nodes_state': List[object],
            'time_stamp': List[int]
        }

        self.attribute_map = {
            'nodes_info': 'nodes_info',
            'jobs_info': 'jobs_info',
            'nodes_state': 'nodes_state',
            'time_stamp': 'time_stamp'
        }

        self._nodes_info = nodes_info
        self._jobs_info = jobs_info
        self._nodes_state = nodes_state
        self._time_stamp = time_stamp

    @classmethod
    def from_dict(cls, dikt) -> 'WebResponseMetrics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WebResponseMetrics of this WebResponseMetrics.  # noqa: E501
        :rtype: WebResponseMetrics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nodes_info(self):
        """Gets the nodes_info of this WebResponseMetrics.


        :return: The nodes_info of this WebResponseMetrics.
        :rtype: List[object]
        """
        return self._nodes_info

    @nodes_info.setter
    def nodes_info(self, nodes_info):
        """Sets the nodes_info of this WebResponseMetrics.


        :param nodes_info: The nodes_info of this WebResponseMetrics.
        :type nodes_info: List[object]
        """

        self._nodes_info = nodes_info

    @property
    def jobs_info(self):
        """Gets the jobs_info of this WebResponseMetrics.


        :return: The jobs_info of this WebResponseMetrics.
        :rtype: List[object]
        """
        return self._jobs_info

    @jobs_info.setter
    def jobs_info(self, jobs_info):
        """Sets the jobs_info of this WebResponseMetrics.


        :param jobs_info: The jobs_info of this WebResponseMetrics.
        :type jobs_info: List[object]
        """

        self._jobs_info = jobs_info

    @property
    def nodes_state(self):
        """Gets the nodes_state of this WebResponseMetrics.


        :return: The nodes_state of this WebResponseMetrics.
        :rtype: List[object]
        """
        return self._nodes_state

    @nodes_state.setter
    def nodes_state(self, nodes_state):
        """Sets the nodes_state of this WebResponseMetrics.


        :param nodes_state: The nodes_state of this WebResponseMetrics.
        :type nodes_state: List[object]
        """

        self._nodes_state = nodes_state

    @property
    def time_stamp(self):
        """Gets the time_stamp of this WebResponseMetrics.


        :return: The time_stamp of this WebResponseMetrics.
        :rtype: List[int]
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp):
        """Sets the time_stamp of this WebResponseMetrics.


        :param time_stamp: The time_stamp of this WebResponseMetrics.
        :type time_stamp: List[int]
        """

        self._time_stamp = time_stamp
